config:
  remote_user: root
  ssh_binary_path: "/usr/bin/ssh"
  scp_binary_path: "/usr/bin/scp"
  rsync_binary_path: "/usr/bin/rsync"
  mysql_binary_path: "/usr/bin/mysql"
  mysqldump_binary_path: "/usr/bin/mysqldump"
  package_manager: aptitude
  aptitude_binary_path: "/usr/bin/aptitude"